# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post__html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_html',
            new_name='htmlrend',
        ),
    ]
