# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_htmlrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='htmlrend',
            field=models.TextField(null=True),
        ),
    ]
