# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 09:12
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_htmlrend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='htmlrend',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_markdown.models.MarkdownField(default=1),
            preserve_default=False,
        ),
    ]
